site:
  title: Antora bug
  start_page: antora-bug::bug.adoc
content:
  sources:
    - url: https://github.com/rbsamoht/antora-bug.git
      branches: main
      start_path: docs
ui:
  bundle:
    url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/master/raw/build/ui-bundle.zip?job=bundle-stable
    snapshot: true
asciidoc:
  extensions:
    - asciidoctor-kroki
  attributes:
    kroki-server-url: http://kroki:8000
    kroki-fetch-diagram: true
    diagramsdir: "docs/modules/ROOT/pages/diagrams"
